name: Build pipeline

on:
    push:
        branches: [release]
    pull_request:
        branches: [release]

jobs:
    deployment_pipeline:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: "16.x"
            - name: yarn install
              run: yarn install
            - name: build
              run: yarn build
